### ISSUE TITLE
After trying the Midas

### ISSUE THREAD

**Issue by BABA3344** [MingxiYe/Midas#2]
After trying the tool,  I noticed it’s taking quite a long time to run and doesn’t seem to be showing any results. I thought it was supposed to analyze transactions ,

Could you clarify what the tool is supposed to do? It'd be helpful to know how long it typically runs and what its main purpose is.

```
 INFO [Stats #0] run time: 0h-11m-26s, clients: 1, corpus: 0, objectives: 0, executions: 15384675, exec/sec: 22.48k
 INFO [Stats #0] run time: 0h-11m-27s, clients: 1, corpus: 0, objectives: 0, executions: 15408744, exec/sec: 22.48k
 INFO [Stats #0] run time: 0h-11m-28s, clients: 1, corpus: 0, objectives: 0, executions: 15433497, exec/sec: 22.48k
 INFO [Stats #0] run time: 0h-11m-29s, clients: 1, corpus: 0, objectives: 0, executions: 15457079, exec/sec: 22.49k
 INFO [Stats #0] run time: 0h-11m-30s, clients: 1, corpus: 0, objectives: 0, executions: 15481438, exec/sec: 22.49k
 INFO [Stats #0] run time: 0h-11m-31s, clients: 1, corpus: 0, objectives: 0, executions: 15505326, exec/sec: 22.49k

```

**Comment by vilotgit** [comment]
I think you can get some answers from the paper (https://dl.acm.org/doi/pdf/10.1145/3650212.368032).
One of the main evaluations used 30 minutes as timeout, so I think 30 minutes can be a reference point.

**Comment by MingxiYe** [comment]
Hi, I think you input the wrong address or fail to connect Etherscan, since the size of the corpus is zero.

**Comment by BABA3344** [comment]
What's the problem?


./metafuzz -o -c ETH --onchain-etherscan-api-key 25Q37J4HSDZRN67QI9XEMN634GKW7W1184 -f --flashloan-price-oracle onchain -t 0xb40b6608B2743E691C9B54DdBDEe7bf03cd79f1c --onchain-block-number 17504368 --target-txn-hash 0x2667e09b617e3bac4fa05f7f4d90dc7e4ede550b058549add90704231b8d6568 --spec-id Latest


 INFO [Stats #0] run time: 2h-47m-38s, clients: 1, corpus: 0, objectives: 0, executions: 224490949, exec/sec: 22.32k
 INFO [Stats #0] run time: 2h-47m-39s, clients: 1, corpus: 0, objectives: 0, executions: 224509024, exec/sec: 22.32k
 INFO [Stats #0] run time: 2h-47m-40s, clients: 1, corpus: 0, objectives: 0, executions: 224533951, exec/sec: 22.32k
 INFO [Stats #0] run time: 2h-47m-41s, clients: 1, corpus: 0, objectives: 0, executions: 224557528, exec/sec: 22.32k
 INFO [Stats #0] run time: 2h-47m-42s, clients: 1, corpus: 0, objectives: 0, executions: 224580820, exec/sec: 22.32k
 INFO [Stats #0] run time: 2h-47m-43s, clients: 1, corpus: 0, objectives: 0, executions: 224603047, exec/sec: 22.32k
 INFO [Stats #0] run time: 2h-47m-44s, clients: 1, corpus: 0, objectives: 0, executions: 224622469, exec/sec: 22.32k
 INFO [Stats #0] run time: 2h-47m-45s, clients: 1, corpus: 0, objectives: 0, executions: 224644427, exec/sec: 22.32k
 INFO [Stats #0] run time: 2h-47m-46s, clients: 1, corpus: 0, objectives: 0, executions: 224660617, exec/sec: 22.32k
 INFO [Stats #0] run time: 2h-47m-47s, clients: 1, corpus: 0, objectives: 0, executions: 224681827, exec/sec: 22.32k
 INFO [Stats #0] run time: 2h-47m-48s, clients: 1, corpus: 0, objectives: 0, executions: 224700803, exec/sec: 22.32k
 INFO [Stats #0] run time: 2h-47m-49s, clients: 1, corpus: 0, objectives: 0, executions: 224717066, exec/sec: 22.32k
 INFO [Stats #0] run time: 2h-47m-50s, clients: 1, corpus: 0, objectives: 0, executions: 224739902, exec/sec: 22.32k
