### ISSUE TITLE
What is the purpose of `target-txn-hash`?

### ISSUE THREAD

**Issue by vilotgit** [MingxiYe/Midas#3]
It seems like the tool requires `target-txn-hash` to run. What transaction hash do we need to input to run the tool?
I tried following the code and it seems like `target-tx-hash` is used to initialize the initial seed corpus.
However, according to the paper, `Midas` uses all historical transactions of a contract to initialize the corpus.
Then, what is the purpose of inputting a specific transaction hash?

**Comment by MingxiYe** [comment]
Hi, we do not use all historical transactions but only part of them. You can choose the latest 50 transactions.

**Comment by vilotgit** [comment]
Do you mean we can just choose any one of the last 50 transactions to run the fuzzer?
Does `target-txn-hash` impact fuzzer performance by any chance?

**Comment by vilotgit** [comment]
I tried running with the latest `transfer` transaction and latest transaction. However, for my target contract, the fuzzer returns error saying that the target transaction should not revert. However, according to etherscan, those transactions are successful transactions (not reverted). Can you provide some guidance on what transaction to select?

**Comment by MingxiYe** [comment]
Hi, could you provide the input related to the target contract and the 'reverted' transaction hash? So that I can review it.

As for the variance caused by the target-txn-hash, yes, it’s similar to the concept of initializing the corpus with high-quality seeds.

**Comment by vilotgit** [comment]
This is one of the test commands I am using.
```
./metafuzz -o -c bsc --onchain-etherscan-api-key <ETHERSCAN_API_KEY> -f --flashloan-price-oracle onchain -t 0xA4f5d4aFd6b9226b3004dD276A9F778EB75f2e9e --onchain-block-number 20302533  --target-txn-hash 0xd5867c33e47850b46042ede3f46a9d1ac71728ee1e590dd7966c6291cca2c617 --onchain-url <RPC_URL>
```
I also tried with transaction hash `0x53162f31d15765b91a0dae754a648072c3b08dfc2e7b73cc572fe51647904135` (transaction at block 20322495), and changing the `--onchain-block-number` to 20291331 (the block right before the original target transaction). However, it all resulted in `The target txn should not revert!`

Thanks!

**Comment by MingxiYe** [comment]
Hi, sorry for the late response. I think this is expected, because midas is trying to run the historical transaction in the specified block, so it might revert.

**Comment by MingxiYe** [comment]
BTW, we are currently trying to push our fuzzer to production and make it fully end-to-end (just one click then it can report bugs). Please feel free to try it out: https://d23e.ch/dashboard/newAuditTask

**Comment by vilotgit** [comment]
Got it. Thanks!
